### ISSUE TITLE
Tutorial post missing semi colon

### ISSUE THREAD

**Issue by steves-bits** [mongodb-developer/mongodb-typescript-example#5]
Not an issue with the code in this repository but with the tutorial documentation in the post at 
https://www.mongodb.com/compatibility/using-typescript-with-mongodb-tutorial

is missing the colon on this line of code 

`export const collections { games?: mongoDB.Collection } = {}`

should be
`export const collections: { games?: mongoDB.Collection } = {}`

the line is missing the name **mongoDB.** 
`   const client: mongoDB.MongoClient = new MongoClient(process.env.DB_CONN_STRING);`

should be
`    const client: mongoDB.MongoClient = new mongoDB.MongoClient(process.env.DB_CONN_STRING);`

**Comment by LuceCarter** [comment]
Thanks for raising @steves-bits 😊! I have asked for the article to be updated with your changes so this should be done in the next few working days.
