### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by jcstange** [mongodb-developer/mongodb-typescript-example#6]
For some reason I was getting this error for some time while trying to build this example. 

I've solved it by adding this on `tsconfig.json`: 
```
{
  "compilerOptions": {
  +  "allowJs": true
  }
}
```

**Comment by LuceCarter** [comment]
Thank you for raising this @jcstange :) I have added this to the tsconfig.json in the finish branch for anyone else trying to build this example and facing the same issue.
